### ISSUE TITLE
Have Enemy Collider Turn Off Light

### ISSUE THREAD

**Issue by Haden2** [Haden2/Spectrum#17]
The collider code is all set up, but I am not getting the right code to call for the flashlights intensity to drop to 0. Perhaps it would be easier to deactivate it like in the roll-a-ball game... Why do I think of the solutions right before work?!

**Comment by thomas-j-sell** [comment]
I got this.

**Comment by thomas-j-sell** [comment]
This actually may require some discussion and refactoring.

**Comment by Haden2** [comment]
Ok, let's discuss. I worked with it for a little bit and tried to recall the flashlight and turn intensity to 0. It wasn't working because it was looking for a light on the enemy player. I even gave the enemy player a light and it didnt do anything. To test it out, I added a public int called testing12. What that did was show that when the enemy's trigger reaches the player, the int number changes to 3. So the collider code works. But where do we go from here? I thought about going about it the other way. Put the code on the flashlight script, or the player script and try that. But realistically there should be a way to do this on the enemy. They should be able to access the players stuff. We just need to figure it out.

**Comment by Haden2** [comment]
Take the game object Bluelight, and deactivate it like the roll-a-ball game. Perhaps set all lighting to a tag and deactivate all objects with that tag. 

Ok, so I tested that out. I killed the player by deactivating it. Now let me try just the light instead of player.

Alright, so I tested this a few times and the light was never turning off. I realized the reason why is because the light may have a tag, but it does not have a collider. I added the collider and now the light turns off. Not only does it turn off, but it deactivates it. Making the press q option obsolete which is what we needed. I have also made a couple changes for the time being only. This includes moving the stopping distance of the enemy navigation from 2 to 2.1. Somehow that makes the world of difference and stops the enemy from running into the player and decreases the chances of getting shot in the air. I also had to increase the radius of the brand new light collider from .2 which looks nice to .5 in order to match the enemies distance.

**Comment by thomas-j-sell** [comment]
Ok, I have a few issues with this solution.

1: The input monitoring in toggle flashlight needs to be refactored to be in PlayerController.  We should have all of our control logic in one place, and playerController seems like the best spot.  We could then repurpose ToggleFlashlight to control the mode of the glasses see #2.

2: I don't think we should have multiple lights attached to our player to correspond with the different modes of the glasses.  I think we should have one light (rename it glasses or spectacles) and script the changes in mode: intensity, color, etc.  This greatly simplifies the logic of dealing with (de)activation and prevents us from being able to have multiple modes active.  This also make future changes much easier, we'll need to change just one object instead of several.
1. This also leads into the discussion about how you want to implement the modes.  Is it just going to be different colored flashlights?  Or do you want to change the scenes directional light with the mode and keep an optional flashlight for dark areas?  Or do we need to find another way to filter what we see?
2. I don't think the light/glasses should have their own collider (especially with multiple lights).  We should be able to script (de)activation off of the players collider.  The girl will be much shorter then us when we get proper models, so in order for the her collider to interact with the glasses at least one of them will have to be extremely oversized.  In the girls case this will give her problems navigating places she should be able to.  In the glasses case it means that the game will be calculating lots of useless collisions as we are near things, this includes the glasses always being in collision with the player model's collider.  Utilizing only one player collider will simplify future tweaks and changes.  This will also put the logic within the player controller, preventing errors in player controller script trying to access lights/glasses that we're deactivated by something else.

I think the currently direction we are going with this feature could lead to lots of headaches in the future as the game gets more and more complex.  It may behoove us to simplify it now.

**Comment by Haden2** [comment]
Haha, I feel like a kid showing his dad some macaroni art and the dad goes, you could have used way less macaroni to complete this and your glue is showing through the sides. *sigh. Ok, I guess I am not sure what you mean by the placement of toggle flashlight because it currently is a child of the player. Are you saying you want it in the first person controller itself so it goes along the scripts like PlayerMovement? I guess that transition wouldn't be too hard. But I feel like we will end up with a lot of scripts on one object.

The regular flashlight is something I can remove. I tweaked it and then I made the new LED light just because I felt like it fit the modern glasses better. I didn't want to remove the original flashlight until I had the ok from you for the new design. It does simplify having to deactivate multiple objects, but it is going to make a ton of scripts for one light and it is going to be harder to code because I know how to change color in a slider, but not in 4 numeric code. That is a bit trickier. 

No they are not just lights. We should have the rest of the modes actually look like they would in that spectrum. So thermal should look like thermal, night vision should look like night vision, and so on. The flashlight was just the easiest to start with because the other ones will involve messing with shaders. 

I can change the shape of the light collider to match the player so it does not matter what the height of the enemy is. So it does not have to be oversized at all. The way I did it was to work around trying to access a different objects game object. If you can figure it out then by all means change it. But I was drawing a really big blank on it before. Something about the GetComponent<ToggleFlashlight> helps us access the script

**Comment by thomas-j-sell** [comment]
I didn't mean to come across so hyper-critical, I just think there are some improvements to do before we say this is done.

**Comment by Haden2** [comment]
No worries, I understand. I have more glue and macaroni here.

**Comment by thomas-j-sell** [comment]
So, currently the camera and flashlight are mounted on our player model pill around face height.  With means that when we appropriately scale our models the light will be much higher on the y axis then any part of the girl.  So those collider's would have to be over sized to interact, which could have it's own problems.

Either way we are already detecting collisions for our player so we can add the detection of the girl there.  It would be a much simpler, and to me, more sensical design.  There's no need to add another script or object to detect collisions we're already capable of detecting.

Also I need a quick clarification.  Is the light going to be part of the glasses or separate?  When the glasses are deactivated will the character still have a basic flashlight or will he/she literally be left in the dark?

**Comment by thomas-j-sell** [comment]
Also it's not too hard to change the light color from a script.  If you look at the sliders on the color picker, the values you need to plug into a script are right there.  So you can use the sliders to find the right color, then just plug those values into the script.

**Comment by Haden2** [comment]
Right, I know the glasses are higher up, but by changing the current collider which is a sphere to something like a cylinder, it can match the players collider so it would be the same as if it was on the player. It does make a lot more sense to just use the player as the collider, I agree. It is just we need to figure out the code for it. When the glasses are deactivated, the player will not have a flashlight. Once the environment is built there is going to be a lot of natural light. More light in some areas than others. But lights will be turned on in rooms and light can come from windows. If you recall, I also had a light on the player from the very beginning of the game. That was intended to act as a normal persons sight in the darkness and to make it so they are not absolutely in the dark. 

Oh right, yeah, just change slider and pick the numbers. I can do that. I was thrown off because red is like 1f,0,0,1f, so it didnt seem like the 225 like I am used to seeing.

**Comment by Haden2** [comment]
So I was able to make the changes to the light collider issue as well as touching up some code on the remove collectable. So now pressing E when the text is shown removes the sphere as well as removes the prompt. Also, the enemy now hunts down the player and when it gets near, turns off the light. No more collisions are made through the light and everything is through the player.

**Comment by Haden2** [comment]
Good to close?

**Comment by thomas-j-sell** [comment]
:+1:
